# Generated by Django 4.0.1 on 2022-03-10 19:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompWebs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamingpost',
            name='Post_Content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
